# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
steps:
    - task: Grunt@0
      displayName: grunt update-config
      inputs:
          gruntFile: $(System.DefaultWorkingDirectory)/drop/electron/$(target)/Gruntfile.js
          targets: update-config
          arguments: --extension-version=$(extension-version) --app-insights-instrumentation-key=$(app-insights-instrumentation-key)
          gruntCli: node_modules/grunt-cli/bin/grunt
      condition: and(always(), eq(variables['target'], 'canary'))
